name: throttle
description: Example showing how to rate-limit jaguar routes using jaguar_throttle
version: 0.0.1
homepage: https://github.com/jaguar-examples/throttle
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.10
  jaguar_throttle: ^0.1.0
  jaguar_hotreload: ^0.1.0

dev_dependencies:
  test: ^0.12.0
