name: throttle
description: Example showing how to rate-limit jaguar routes using jaguar_throttle
version: 0.0.1-dev
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.9
  jaguar_throttle: #^0.0.1
    path: ../jaguar_throttle

dev_dependencies:
  test: ^0.12.0
